### ISSUE TITLE
Project linter

### ISSUE THREAD

**Issue by SomeoneWeird** [nodepolus/nodepolus_old#15]
We obviously need to pick a linter to use for the project, I'm going to throw out [StandardJS](https://standardjs.com/) and [Prettier](https://prettier.io/) as highly recommended options.

Both standard and prettier use 2 spaces for indentation which I know @roobscoob and @Sanae6 seem to be against, but it's pretty much what the JS community as a whole has agreed on. Potentially open to 4 spaces though :)

**Comment by Sanae6** [comment]
I'm oblivious to the 2 space indentation standard in the community, and it's more of a personal preference for me since I never work in 2 space.

**Comment by SomeoneWeird** [comment]
Added prettier in 3aaa7a5f4955c989fb498b76342f4630372b5def
