### ISSUE TITLE
Venting does not update position values

### ISSUE THREAD

**Issue by SomeoneWeird** [nodepolus/nodepolus_old#21]
Venting currently works for an imposter, but when leaving a different vent than the one they got into, the imposters position is not updated on other clients.

As soon as the imposter moves, a movement packet is sent and they teleport on other clients.

**Comment by SomeoneWeird** [comment]
The vents also animate correctly on entry/exit of an imposter, only position is busted.

**Comment by roobscoob** [comment]
To add on this exiting a vent may break the movement packets subsequently, sticking that player in a specific room for the rest of the players.

**Comment by roobscoob** [comment]
https://github.com/roobscoob/NodePolus/commit/1098b42b8d5ec3111520dd6f19578b1e74d92276 fixes this
