### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by miguelkix30** [nodepolus/nodepolus_old#60]
When i start the server it crashes.
[2020-12-14T13_19_57_058Z-debug.log](https://github.com/NodePolus/NodePolus/files/5689104/2020-12-14T13_19_57_058Z-debug.log)

**Comment by randy-halim** [comment]
What exactly are you doing? Did you run `npm install` to get all the required packages?

**Comment by miguelkix30** [comment]
yes

**Comment by miguelkix30** [comment]
i cloned and i did `npm install` and i run it and it crashes

**Comment by randy-halim** [comment]
Strange, it works just fine for me... are you running the latest LTS version of node (v14)? What command are you using to start?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by roobscoob** [comment]
```
23 verbose stack Error: command failed
23 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
23 verbose stack     at ChildProcess.emit (node:events:376:20)
23 verbose stack     at maybeClose (node:internal/child_process:1063:16)
23 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
```
these are all calls to Node internals. This is likely an issue with your node/npm installation and not NodePolus

**Comment by randy-halim** [comment]
Huh, that must be the issue... couldn't replicate it on either my Windows install or my WSL distro. @miguelkix30 - this may be outside the jurisdiction of NodePolus; try reinstalling Node.

**Comment by miguelkix30** [comment]
i reinstalled 1891651 times in diferent versions. 14.15.1 LTS and 15.0.1 and it still doesnt work

**Comment by edqx** [comment]
I think you have to use g++ rather than gcc
